version: "3.8"

networks:
  backend:
    driver: bridge

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - backend
    environment:
      - REACT_APP_PREDICT_API=http://backend:5000/predict

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - backend
